/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5c77d8cc37d35e0f5d2c24d9a50532c8)
interface __BaseEnv_Env {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	DEX_API: Fetcher /* xcpdex-api */;
	XCP_API: Fetcher /* xcp-api */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
