ALTER TABLE orders ADD COLUMN give_quantity REAL NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN get_quantity REAL NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN remaining REAL NOT NULL DEFAULT 0;
