/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 94de01f9f0c81d0949061395ab7425a4)
interface __BaseEnv_Env {
	XCPDEX_API: Fetcher /* xcpdex-api */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
