/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 845584b96eea292c91495752873bee36)
interface __BaseEnv_Env {
	DB: D1Database;
	CP_API_BASE: "https://api.counterparty.io:4000/v2";
	SITE_PRESENCE: DurableObjectNamespace<import("./src/index").SitePresence>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SitePresence";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CP_API_BASE">> {}
}
