name = "xcpdex-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[limits]
cpu_ms = 300000

[triggers]
crons = ["*/2 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xcpdex"
database_id = "c30d6223-aee2-4ee5-a9a2-e6ff2ce3dede"
migrations_dir = "migrations"

[vars]
CP_API_BASE = "https://api.counterparty.io:4000/v2"
